### ISSUE TITLE
Too many direct dependencies

### ISSUE THREAD

**Issue by quchen** [quchen/acme-everything#1]
The dependency footprint is quite unhandy. By taking into account transitive dependencies, the number of explicit dependencies could be dramatically reduced.

**Comment by deepfire** [comment]
An important consideration is that it's easier to maintain this way -- because once we start omitting implicit dependencies, we'll need to periodically revalidate the totality property.

What is worse, when the property is determined to be broken, we need to compute the minimum cover of the transitive closure.

I don't see an economic way to achieve this manually.

**Comment by quchen** [comment]
We need to periodically update the main feature of the package, namely depending on everything, already. Minimizing the result is just a cleanup step ("take all nodes, and remove all of them that appear as a dependency somewhere").
